### ISSUE TITLE
Server returned responce code: 400

### ISSUE THREAD

**Issue by ZombieStriker** [ArsenArsen/Updater#4]
I have been doing tests trying to figure out why some of the servers were not downloading the newest versions of my plugin.  When I changed the plugin version in the plugin.yml to, I got it this error message.

 The same error appears every time I reload the server, and happens for all the other plugins I have when I change their versions. 

>  [17:54:18] [Craft Scheduler Thread - 2/INFO]: [PixelPrinter] Starting update of PixelPrinter
[17:54:19] [Craft Scheduler Thread - 2/ERROR]: [PixelPrinter] Couldn't download update for PixelPrinter
java.io.IOException: Server returned HTTP response code: 400 for URL: http://servermods.cursecdn.com/files/2363/153/PixelPrinter v1.0.12.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_112]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_112]
	at java.net.URL.openStream(Unknown Source) ~[?:1.8.0_112]
	at me.zombie_striker.pixelprinter.Updater.download(Updater.java:257) [PixelPrinter%20v1.0.12.jar:?]
	at me.zombie_striker.pixelprinter.Updater.access$3(Updater.java:247) [PixelPrinter%20v1.0.12.jar:?]
	at me.zombie_striker.pixelprinter.Updater$1.run(Updater.java:231) [PixelPrinter%20v1.0.12.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [Spigot.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Spigot.jar:git-Spigot-7d78b81-e2a288c]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_112]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
[17:54:19] [Craft Scheduler Thread - 2/INFO]: [PixelPrinter] Update done! Result: IOERROR

**Comment by ArsenArsen** [comment]
Look at that, they changed how moved resources work! Thanks, working on it now!

**Comment by ArsenArsen** [comment]
Ugh, it auto closed.. :clap: 

Anyways, try with `1.1.6-R0.1-SNAPSHOT` as your version.

**Comment by ZombieStriker** [comment]
Tried the new snapshot. Still getting the 400 response code. 

>[2017-01-04 15:28:15] Failed to update PixelPrinter! java.io.IOException: Server returned HTTP response code: 400 for URL: http://servermods.cursecdn.com/files/2363/153/PixelPrinter v1.0.12.jar
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at me.zombie_striker.pixelprinter.Updater.downloadIsSeperateBecauseGotoGotRemoved(Updater.java:301)
	at me.zombie_striker.pixelprinter.Updater.download(Updater.java:257)
	at me.zombie_striker.pixelprinter.Updater.access$3(Updater.java:246)
	at me.zombie_striker.pixelprinter.Updater$1.run(Updater.java:230)
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://servermods.cursecdn.com/files/2363/153/PixelPrinter v1.0.12.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at me.zombie_striker.pixelprinter.Updater.downloadIsSeperateBecauseGotoGotRemoved(Updater.java:296)
	... 8 more

**Comment by ArsenArsen** [comment]
Okay.... This is due to the space in the URL... I think I have a solution.

http://i.imgur.com/jkr5xyH.png

**Comment by ZombieStriker** [comment]
I've tested it with two of my plugins, This seems to have fixed the problem.
